version: "3"
services:
  web:
    build: .
    command: puma -b tcp://0.0.0.0:9292
    ports:
      - 9292:9292
    external_links:
      - mysql-dev:db
    volumes:
      - app_data:/inventory_manager

volumes:
  app_data:
    external:
      name: app-dev-data

networks:
  default:
    external:
      name: cloud-dev
