version: "2"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
  web:
    build: .
    command: rackup
    ports:
      - "9292:9292"
    links:
      - db
    volumes:
      - /Users/anthonyikeda/work/git_cloud/docker_rails_blog_api/inventory_manager:/inventory_manager

