# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: false

development:
  <<: *default
  database: inventory_manager_dev
  username: im_user
  password: aB6yog4Quex5
  host: db

test:
  <<: *default
  database: inventory_manager_test
  username: im_user
  password: aB6yog4Quex5
  host: db

production:
  <<: *default
  database: inventory_manager
  username: im_user
  password: aB6yog4Quex5
  host: db
