source 'https://rubygems.org'

gem 'puma'
gem 'mysql2'

gem 'rails', '~> 5.0.1'

gem 'spring', :group => :development

gem 'sqlite3'

gem 'listen', :group => :development

gem 'byebug', :groups => [:development, :test]

gem 'rspec-rails', '>= 3.5.0', :group => :development
gem 'factory_girl_rails', :group => :development

gem 'active_model_serializers'
gem 'rack-cors'

